name = "Hugo Heroicons"
license = "MIT"
licenselink = "https://github.com/fawkssc/hugo-heroicons/LICENSE"
description = "Hugo SVG partials to embed Heroicons."
homepage = "https://github.com/fawkssc/hugo-heroicons"
tags = ["tailwind", "hero", "icons", "heroicons"]
features = ["embedded svg"]

[author]
  name = "Fawks Software Consulting"
  homepage = "https://www.fawkssoftwareconsulting.com"

[original]
  name = "Tailwind Labs"
  homepage = "https://heroicons.com"
  repo = "https://github.com/tailwindlabs/heroicons"
